### ISSUE TITLE
Eureka is not compiling in Xcode 9.3

### ISSUE THREAD

**Issue by moonvader** [xmartlabs/Eureka#1501]
**Environment:** 
- Xcode Version 9.3 (9E145)
- Swift Language Version = 4.1 (is set for Eureka framework target build settings in Xcode)

Eureka is installed with cocoapods with
_pod 'Eureka'_
and 
_pod update_

While installing log says _Using Eureka (3.0.0)_

When try to compile I got

> 'Sequence' requires the types '[BaseRow]' and 'ArraySlice<B

and 

> Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

as well as suggestion to 

> Add '@ objc' to expose this instance method to Objective-C

**Comment by mats-claassen** [comment]
You should use Eureka 4.1.1. Eureka works with Swift 4.1 from version 4.1.0 on.

**Comment by SSamanta** [comment]
Are not there any support for Xcode 9.3 and swift 3.3 version.

**Comment by gityubj** [comment]
I have the same problem using xcode 9.3 version. Suggest a solution.

**Comment by dote** [comment]
I have updated Eureka to 4.1.1, changed Swift to 4.1, and I get the /Pods/Eureka/Source/Core/Section.swift:247:1: Type 'Section' does not conform to protocol 'RangeReplaceableCollection' error. Please advise. Thank you!

**Comment by mats-claassen** [comment]
Sorry, guys, but I can't reproduce this. Created new project -> added Eureka pod to podfile -> pod install -> Add a row to a view controller -> builds fine.

This error you are mentioning happened with the codebase prior to Eureka 4.1.1 when trying to build with Swift 4.1 I think. Could you try to make sure the Eureka source code Cocoapods is downloading is effectively 4.1.1?

**Comment by mats-claassen** [comment]
For those compiling in Swift 3.3, use Eureka's Swift-3.3 branch

**Comment by ReissZ** [comment]
@mats-claassen Yes, I can confirm I have Eureka 4.1.1 installed. I am running Swift 4.1 and the Type 'Section' does not conform to protocol 'RangeReplaceableCollection' issue persists. Thanks!

**Comment by bitbibit** [comment]
Same boat as @ReissZ here.

**Comment by dote** [comment]
Same confirmation here as @ReissZ, thank you.

**Comment by Abbaspoor89** [comment]
Any news?
I should deliver my project asap
@mats-claassen

**Comment by mats-claassen** [comment]
Could anyone upload a sample project as we cannot reproduce this?

**Comment by mats-claassen** [comment]
Maybe #1495 or #1498 are of some help

**Comment by dansinclair25** [comment]
I've found that making sure the `Swift Language Version` of the Eureka framework in Xcode is set to `Swift 4.1` and doing a clean of the project fixed the `Type 'Section' does not conform to protocol 'RangeReplaceableCollection` issue.

**Comment by ReissZ** [comment]
Thanks @dsmailes and @mats-claassen for solving this issue [here].(https://github.com/xmartlabs/Eureka/issues/1498)

For those who facing same problem as me: 
In the podfile, try:

pod 'Eureka' to install Eureka 4.1.1 with a post_install hook:

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Eureka'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end

**Comment by sarbogast** [comment]
I already had a working project using Eureka 4.0 and everything was working smoothly. After a few weeks without touching the project, now it doesn't build anymore and I had this "Type 'Section' does not conform to protocol 'RangeReplaceableCollection'" error. So I upgraded Eureka to version 4.1.1 as suggested, but now it's even worse. Now I have 34 compilation errors in Eureka:

![screenshot 2018-04-16 18 10 53](https://user-images.githubusercontent.com/143758/38821690-869c4d54-41a1-11e8-821a-d445610d3412.png)

What's going on?

**Comment by masterwali** [comment]
Fixed!
Xcode 9.3
Swift 3.3

I had this error "Type 'Section' does not conform to protocol 'RangeReplaceableCollection' errors showed up.

fixed by using this in my pod

pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift-3.3'

**Comment by Abbaspoor89** [comment]
Thanks @masterwali

**Comment by djaygit** [comment]
was anyone able to install it in xcode 9.3.1?

**Comment by mats-claassen** [comment]
Yes, no problem. Do you have any problems?

**Comment by Jamarsoft** [comment]
Im having this problem for a client, Eureka just isn't building, I suspect theres a version mismatch somewhere.

<img width="1428" alt="screen shot 2018-09-25 at 10 13 57" src="https://user-images.githubusercontent.com/1452462/46025414-c2e82080-c0e0-11e8-9efe-6247f3167e96.png">

**Comment by Jamarsoft** [comment]
Im having similar issues with Eureka 4.3 not building.  I assume by the errors theres a version mismatch somewhere.
<img width="274" alt="screen shot 2018-09-25 at 16 35 35" src="https://user-images.githubusercontent.com/1452462/46025548-1bb7b900-c0e1-11e8-881a-70c9601cca70.png">

**Comment by mats-claassen** [comment]
Use Eureka 4.2 for older versions of Xcode. 4.3 is for Xcode 10

**Comment by jaketn** [comment]
I'm also fairly new to github. How do I download an older version? I tried cloning a different branch but am not sure how to do this.

**Comment by masterwali** [comment]
@jaketn go back to the main page > Branch > Tags select version > Download or get url

**Comment by onvika** [comment]
Hi, I am using swift 4.1 and Xcode 9.4.1
if I use Eureka '4.2' I get bunches of errors
if I use Eureka '4.0' I get this: Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

I have already tried this: pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift-3.3'

I have include this: post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Eureka'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end

I think I have read and tried almost all, and yet... I can not solve it ;/
any ideas ??

**Comment by mats-claassen** [comment]
Eureka 4.1 adds support for Swift 4.1. You should try with `4.1.0`, `4.1.1` or `4.2.0`. I do not have that version of Xcode around to try it, so I don't know which errors you are getting, sorry.

**Comment by onvika** [comment]
I have already tried all of them and yet none work... I actually gave up
