### PR TITLE
Fixed array slice for Swift 3.2

### LINKED ISSUE #1082: Fails to compile in Xcode 9
With Swift version 3.2 as compiled with Xcode 9 - Beta 1.
Installed as a pod with use_framworks!

```
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/Section.swift:206:1: error: 'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent
extension Section : MutableCollection, BidirectionalCollection {
^
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/Section.swift:206:1: note: requirement specified as 'Self.SubSequence' == 'Self.SubSequence.SubSequence' [with Self = Section]
extension Section : MutableCollection, BidirectionalCollection {
^
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/SelectableSection.swift:65:43: error: associated type 'Self.SubSequence.SubSequence' cannot be equal to both 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>'
extension SelectableSectionType where Self: Section, Self.Iterator == IndexingIterator<Section>, Self.Iterator.Element == BaseRow {
                                          ^
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/Section.swift:206:1: error: 'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent
extension Section : MutableCollection, BidirectionalCollection {
^
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/Section.swift:206:1: note: requirement specified as 'Self.SubSequence' == 'Self.SubSequence.SubSequence' [with Self = Section]
extension Section : MutableCollection, BidirectionalCollection {
```

### PR DESCRIPTION
**Pull request by ivanbruel**
This should fix #1082, I've tried running the example app on an iOS 11 beta device and it all seemed to be working properly.
I could not run the app or the unit tests on the simulator due to an Xcode problem though.

### CODE REVIEW

**Comment by mats-claassen** [comment]
We should merge this into another branch like `swift3.2`

**Comment by mrgrauel** [comment]
Isn't it safe to be build with swift 3.1? Shouldn't be a problem to be in the master.
