### ISSUE TITLE
Eureka 5.2.1 and RichTextRow issue

### ISSUE THREAD

**Issue by kira6783** [xmartlabs/Eureka#2051]
i have been developing ios app with Eureka Form and also used RichTextRow
when i add only Eureka it install 5.2.1 pod
but later if i add pod RichTextRow it degraded Eureka to 4.3.1

in Eureka 4.3.1 if i archive the build in xcode 11.5 it has the following issue

for expression at [/Pods/Eureka/Source/Core/RowType.swift:238:35 - line:238:82] RangeText="{ [unowned self] in  callback(self.cell, self) "

with error: Segmentation fault: 11 (in target 'Eureka' from project 'Pods') in Eureka 4.3.1

Before submitting issues ...

- Make sure you are using Eureka [latest release](https://github.com/xmartlabs/Eureka/releases) or master branch version.
- Make sure your Xcode version is the latest stable one.
- Check if the issue was [already reported or fixed](https://github.com/xmartlabs/Eureka/issues?utf8=%E2%9C%93&q=is%3Aissue). We add labels to each issue in order to easily find related issues. If you found a match add a brief comment "I have the same problem" or "+1".

When submitting issues, please provide the following information to help maintainers to fix the problem faster:

- Environment: Eureka, Xcode and iOS version you are using.
- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.
- Any other additional detail such as your eureka form/section/row code that you think it would be useful to understand and solve the problem.

**Comment by mats-claassen** [comment]
Hey @kira6783 thanks for reporting this. I saw you opened an issue in the RichTextRow repo which is what you have to do. The issue should be tracked there as it is not an issue of Eureka itself.

**Comment by kira6783** [comment]
Thanks resolved now
