### ISSUE TITLE
Fails to compile in Xcode 9

### ISSUE THREAD

**Issue by geoffmacd** [xmartlabs/Eureka#1082]
With Swift version 3.2 as compiled with Xcode 9 - Beta 1.
Installed as a pod with use_framworks!

```
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/Section.swift:206:1: error: 'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent
extension Section : MutableCollection, BidirectionalCollection {
^
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/Section.swift:206:1: note: requirement specified as 'Self.SubSequence' == 'Self.SubSequence.SubSequence' [with Self = Section]
extension Section : MutableCollection, BidirectionalCollection {
^
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/SelectableSection.swift:65:43: error: associated type 'Self.SubSequence.SubSequence' cannot be equal to both 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>'
extension SelectableSectionType where Self: Section, Self.Iterator == IndexingIterator<Section>, Self.Iterator.Element == BaseRow {
                                          ^
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/Section.swift:206:1: error: 'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent
extension Section : MutableCollection, BidirectionalCollection {
^
/Users/geoffmacdonald/imgur-ios/Pods/Eureka/Source/Core/Section.swift:206:1: note: requirement specified as 'Self.SubSequence' == 'Self.SubSequence.SubSequence' [with Self = Section]
extension Section : MutableCollection, BidirectionalCollection {
```

**Comment by ivanbruel** [comment]
This seemed to be an issue of Protocol conformance with `Collection` where the subscript should return an `ArraySlice` instead of an actual `Array` type.
I've fixed it, let me know if that works out for all of you working under Xcode 9.

**Comment by mats-claassen** [comment]
Hi, `swift3.2` branch works with Xcode 9 beta.

**Comment by geoffmacd** [comment]
thanks guys

**Comment by mahirekici** [comment]
I have this problem ?

Xcode  9 




requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent

**Comment by farshadjahanmanesh** [comment]
me too

**Comment by yoman07** [comment]
xcode 9 beta 4 doesn't work

**Comment by pedrodelavega** [comment]
FYI, xcode 9 beta 5 is working with swift3.2 branch

**Comment by alexvazquez** [comment]
How can I update Pod Eureka to Beta 5?

**Comment by chappejw** [comment]
Having the same issue on the newly released Xcode 9...

`'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent`

**Comment by halldorg** [comment]
Same here on the released xcode 9

'Collection' requires the types 'Section.SubSequence' (aka 'Array<BaseRow>') and 'ArraySlice<BaseRow>' be equivalent

**Comment by eflyjason** [comment]
`pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Xcode9-Swift4'` works for me :)

**Comment by johndpope** [comment]
did anyone get above xcode swift 3-2 branch working with ImageRow?
Analyzing dependencies
Pre-downloading: `Eureka` from `https://github.com/xmartlabs/Eureka.git`, branch `Xcode9-Swift3_2`
[!] Unable to satisfy the following requirements:

- `Eureka (from `https://github.com/xmartlabs/Eureka.git`, branch `Xcode9-Swift3_2`)` required by `Podfile`
- `Eureka (~> 4.0)` required by `ImageRow (3.0.0)`

**Comment by elalienx** [comment]
The problems appears again in Xcode 9.4 and Swift 4.2

**Comment by mats-claassen** [comment]
Swift 4.2 is available in Xcode 10.

There is also a Swift-4.2 branch

**Comment by FrancoisClement** [comment]
Same problem in xCode 9.4, Swift 4.1
@elalienx did you find a fix ?

**Comment by mats-claassen** [comment]
For Xcode 10 use Eureka 4.3. For older versions use 4.2.
