### ISSUE TITLE
Still getting Command CompileSwift failed with a nonzero exit code after updating to 4.3.0

### ISSUE THREAD

**Issue by AbdullahFaqeir** [xmartlabs/Eureka#1669]
OS macOS Majove 
Xcode 10
iOS 12
Eureka 4.3.0

<img width="376" alt="screen shot 2018-09-26 at 5 54 47 pm" src="https://user-images.githubusercontent.com/1428547/46088543-45421480-c1b5-11e8-9705-b71e9260518f.png">

**Comment by mats-claassen** [comment]
Possible duplicate of #1667

**Comment by AbdullahFaqeir** [comment]
Didn't work :/

**Comment by mtnbarreto** [comment]
@AbdullahFaqeir Could you please share more info about the compilation errors..?  so we can help more _efficiently_

**Comment by mtnbarreto** [comment]
Close due to lack of response.

**Comment by AbdullahFaqeir** [comment]
I apologize for the late reply, I managed to run the app as other hidden errors was effecting it.

Thank you.
