### ISSUE TITLE
Xcode 9.3 compilation error

### ISSUE THREAD

**Issue by RexNexstream** [xmartlabs/Eureka#1498]
Eureka 4.1.1
Xcode 9.3
![screen shot 2018-04-03 at 12 18 17 pm](https://user-images.githubusercontent.com/12932221/38229073-6cecba6e-3739-11e8-9487-c1e1305e0aaf.png)
![screen shot 2018-04-03 at 12 18 25 pm](https://user-images.githubusercontent.com/12932221/38229074-6d282f68-3739-11e8-9365-af8060452ea6.png)
![screen shot 2018-04-03 at 12 19 41 pm](https://user-images.githubusercontent.com/12932221/38229076-6d59bc2c-3739-11e8-95f9-41eaa7c41f6e.png)

I still facing compilation error after update to 4.1.1 . Please advise. thank you

**Comment by mats-claassen** [comment]
How are you installing Eureka?
I suppose in the Xcode build settings or in the dependency manager config it is specified to build Eureka with the wrong Swift version.

**Comment by dsmailes** [comment]
mats-claassen has the correct answer. You need to change the Swift version to 4.1 in the Pods build settings.

**Comment by RexNexstream** [comment]
Thank @dsmailes and @mats-claassen .

For those who facing same problem with me , you try with a post_install hook in podfile:

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Eureka'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end

**Comment by ReissZ** [comment]
@RexNexstream this worked for me! One thing to note is make sure you still have pod 'Eureka' in your target as well. Thanks!!

**Comment by onvika** [comment]
Hi, I am using swift 4.1 and Xcode 9.4.1
if I use Eureka '4.2' I get bunches of errors
if I use Eureka '4.0' I get this: Type 'Section' does not conform to protocol 'RangeReplaceableCollection'

I have already tried this: pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'Swift-3.3'

I have include this: post_install do |installer|
installer.pods_project.targets.each do |target|
if target.name == 'Eureka'
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '4.1'
end
end
end
end

I think I have read and tried almost all, and yet... I can not solve it ;/
any ideas ??
